### ISSUE TITLE
Cannot make it working with webpack/ES6

### ISSUE THREAD

**Issue by alex88** [fraywing/textAngular#1056]
So I've added

```
require('textangular/dist/textAngular-rangy.min');
require('textangular/dist/textAngular-sanitize');
require('textAngular/dist/textAngular');
```

into my webpack entry file, and I get:

```
textAngular-rangy.min.js:2 Uncaught Error: Cannot find module "./rangy-core"`
```

in the console, is there something wrong?

**Comment by alex88** [comment]
Nevermind, seems that from other comments the way to make it working now is:

```
// Horrible hack, move away from textAngular ASAP, so poorly written
(() => {
  window.taTools = {};
  window.rangy = require('rangy/lib/rangy-core');
})();
require('rangy/lib/rangy-selectionsaverestore');
require('textangular/dist/textAngular-sanitize');
require('textAngular/dist/textAngularSetup');
require('textAngular/dist/textAngular');
```
not very beautiful but it works!

**Comment by RynoRn** [comment]
@alex88  Ah I've been struggling my whole day before I found this. Thanks man!

**Comment by alex88** [comment]
@RynoRn lol and your notification made me see that I left the "rant" code comment in the github comment :laughing: 
Np! Took me a while to figure that out!

**Comment by RynoRn** [comment]
Yeah, that comment made me laugh :D

**Comment by Kamilius** [comment]
This solution is actually a bad one, for those who are testing their code with `Karma`. On modules, which are utilizing controller with `TextAngular` connected this way - tests are crashing with message: "textAngular Error: A unique name is required for a Tool Definition"

**Comment by alex88** [comment]
@Kamilius any better one?

**Comment by Kamilius** [comment]
@alex88 for now, didn't found a proper solution. But still trying :)

**Comment by peturh** [comment]
@alex88 solutions didn't work completely for me. I installed `textangular@^1.5.0` from `npm` and `rangy@^1.3.0`.

I have this in my entry file.

```
window.taTools = {};
window.rangy = require('rangy/lib/rangy-core');
require('rangy/lib/rangy-selectionsaverestore');
require('textangular/dist/textAngular-sanitize');
require('textangular/dist/textAngularSetup');
require('textangular/dist/textAngular');
```

If I have the function declaration around like this:

```
 (() => {
  window.taTools = {};
  window.rangy = require('rangy/lib/rangy-core');
})();
```
I get

```
bundle.js:62 Uncaught ReferenceError: require is not defined(anonymous function) @ bundle.js:62(anonymous function) @ bundle.js:63__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:40(anonymous function) @ bundle.js:43
bundle.js:178 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module textAngular due to:
Error: [$injector:nomod] Module 'textAngular' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.3/$injector/nomod?p0=textAngular
    at http://localhost:9090/bundle.js:178:13
    at http://localhost:9090/bundle.js:2144:18
    at ensure (http://localhost:9090/bundle.js:2068:39)
    at module (http://localhost:9090/bundle.js:2142:15)
    at http://localhost:9090/bundle.js:4634:23
    at forEach (http://localhost:9090/bundle.js:431:21)
    at loadModules (http://localhost:9090/bundle.js:4618:6)
    at http://localhost:9090/bundle.js:4635:41
    at forEach (http://localhost:9090/bundle.js:431:21)
    at loadModules (http://localhost:9090/bundle.js:4618:6)
http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=textAngular&p1=Erro…20at%20loadModules%20(http%3A%2F%2Flocalhost%3A9090%2Fbundle.js%3A4618%3A6)
    at http://localhost:9090/bundle.js:178:13
    at http://localhost:9090/bundle.js:4657:16
    at forEach (http://localhost:9090/bundle.js:431:21)
    at loadModules (http://localhost:9090/bundle.js:4618:6)
    at http://localhost:9090/bundle.js:4635:41
    at forEach (http://localhost:9090/bundle.js:431:21)
    at loadModules (http://localhost:9090/bundle.js:4618:6)
    at createInjector (http://localhost:9090/bundle.js:4540:20)
    at doBootstrap (http://localhost:9090/bundle.js:1820:21)
    at bootstrap (http://localhost:9090/bundle.js:1841:13)
http://errors.angularjs.org/1.5.3/$injector/modulerr?p0=app&p1=Error%3A%20%…%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A9090%2Fbundle.js%3A1841%3A13)(anonymous function) @ bundle.js:178(anonymous function) @ bundle.js:4657forEach @ bundle.js:431loadModules @ bundle.js:4618createInjector @ bundle.js:4540doBootstrap @ bundle.js:1820bootstrap @ bundle.js:1841angularInit @ bundle.js:1726(anonymous function) @ bundle.js:30819trigger @ bundle.js:3237defaultHandlerWrapper @ bundle.js:3527eventHandler @ bundle.js:3515
```

**Comment by noam3127** [comment]
@Kamilius I'm running into that error you describe when running karma tests. Did you ever figure out an alternative solution?

**Comment by Kamilius** [comment]
@noam3127 as far as I remember - no. We still have this, relatively small module without proper unit tests

**Comment by fidaurhaq** [comment]
@noam3127 @Kamilius 

I figured out a workaround so that it won't throw 

> "textAngular Error: A unique name is required for a Tool Definition".

 The module that has textAngular injected into it, can be loaded using beforeAll if you're using Jasmine. This will make sure that textAngular is not re-instantiated with each test. 

So If you have an app
`angular.module('app', ['textAngular'])`

then in your tests, you will have:

`beforeAll(module('app'));`

Be-careful with this approach since you may leak state between specs.
