### ISSUE TITLE
v1.5.x breaks browserify

### ISSUE THREAD

**Issue by craigcabrey** [fraywing/textAngular#1068]
Upgrading to 1.5.x causes a `SyntaxError` for browserify (12.0.2) builds.

```
SyntaxError: Unexpected token (14:27399) while parsing C:\[...]\node_modules\textangular\dist\textAngular.min.js while parsing file: C:\[...]\node_modules\textangular\dist\textAngular.min.js
    at DestroyableTransform.end [as _flush] (C:\[...]\node_modules\insert-module-globals\index.js:96:21)
    at DestroyableTransform.<anonymous> (C:\[...]\node_modules\readable-stream\lib\_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at prefinish (C:\[...]\node_modules\readable-stream\lib\_stream_writable.js:501:12)
    at finishMaybe (C:\[...]\node_modules\readable-stream\lib\_stream_writable.js:509:7)
    at endWritable (C:\[...]\node_modules\readable-stream\lib\_stream_writable.js:521:3)
    at DestroyableTransform.Writable.end (C:\[...]\node_modules\readable-stream\lib\_stream_writable.js:486:5)
    at DuplexWrapper.onend (C:\[...]\node_modules\readable-stream\lib\_stream_readable.js:545:10)
```

Downgrading to 1.4.6 resolves the issue.

**Comment by pbassut** [comment]
I don't use browserify. Could you set up and example or walk me through on how to reproduce this? 
Thanks.
