### ISSUE TITLE
When hit textAngular's toolbar, it occurs: TypeError: this.action is not a function

### ISSUE THREAD

**Issue by maxiaolin0615** [fraywing/textAngular#1092]
I have tried many times and searched a lot, but still didn't succeeded. I greatly appreciate if you could show me some solutions. Thank you very much.

Details can be found as below:

textAngular is a wonderful work. I try to integrate it in my project, but got the following error when I hit the button in the toolbar of textAngular (which didn't show correctly, although):
```
TypeError: this.action is not a function
    at Scope.executeAction (http://localhost:8080/bower_components/textAngular/dist/textAngular.js:420:18)
    at fn (eval at <anonymous> (http://localhost:8080/bower_components/angularjs/angular.js:14086:15), <anonymous>:4:230)
    at expensiveCheckFn (http://localhost:8080/bower_components/angularjs/angular.js:15076:18)
    at callback (http://localhost:8080/bower_components/angularjs/angular.js:24546:17)
    at Scope.$eval (http://localhost:8080/bower_components/angularjs/angular.js:16820:28)
    at Scope.$apply (http://localhost:8080/bower_components/angularjs/angular.js:16920:25)
    at HTMLButtonElement.<anonymous> (http://localhost:8080/bower_components/angularjs/angular.js:24551:23)
    at defaultHandlerWrapper (http://localhost:8080/bower_components/angularjs/angular.js:3398:11)
    at HTMLButtonElement.eventHandler (http://localhost:8080/bower_components/angularjs/angular.js:3386:9)
```

And the toolbars don't show correctly, like this:
![image](https://cloud.githubusercontent.com/assets/12896804/13379718/67151fc2-de68-11e5-8880-5de76eb0953f.png)

The following is some information about my project:
1. AnuglarJS version: v1.5.0
2. I use angularAMD, and in the main.js:
   ```
 require.config({
    baseUrl: '/js/',
    paths : {
           // some other modules
         'angular': '/bower_components/angularjs/angular',
        'rangy-core': '/bower_components/rangy/rangy-core.min',
        'rangy-selectionsave': '/bower_components/rangy/rangy-selectionsaverestore.min',
        'textAngular-sanitize': '/bower_components/textAngular/dist/textAngular-sanitize.min',
        'textAngularSetup': '/bower_components/textAngular/dist/textAngularSetup',
        'textAngular': '/bower_components/textAngular/dist/textAngular'
    },

    shim : {
        'angular': {exports: 'angular'},
        //  some other configurations
     'textAngular-sanitize': {
            deps: ['angular']
        },
        'textAngularSetup': {
            deps: ['angular']
        },
        'textAngular': {
            exports: 'textAngular',
            deps: ['angular', 'textAngular-sanitize', 'textAngularSetup']
        }
},

    map : {
        '*': {

        }
    }
});

require(['./app','rangy-core', 'rangy-selectionsave'], function(app,rangyCore) { //init the application
    app.init();
    window.rangy = rangyCore;
});
```

3. In the .html file (with thymeleaf: <html  xmlns:th="http://www.thymeleaf.org">), I include:
` <link rel='stylesheet' type="text/css" href='/bower_components/textAngular/dist/textAngular.css'/>`

`<text-angular ta-text-editor-setup="textAreaSetup" ng-model="selectedLaw.content"></text-angular>`

4. In the .js file, I include:
```
define([
    'app',
    'textAngular',
    'directive/editable',
    'directive/selectable',
    'directive/page_select',
    'lib/smart-table'
], function(app,textAngular) {
```

5. Above is the code after several tries. And, at the very first try, I follow the instruction in your github, like including the .css and .js files using <script>, but it doesn't work.

**Comment by pbassut** [comment]
Did you define a new button? If so, did you specify action as a function?

Enviado do meu iPhone

**Comment by maxiaolin0615** [comment]
The buttons are the original tool buttons in the textAngular, expected like this:
![image](https://cloud.githubusercontent.com/assets/12896804/13379826/2550be30-de6c-11e5-9052-32316fc0eb6d.png)

**Comment by pbassut** [comment]
What button is it specifically? Anyone?

Enviado do meu iPhone

**Comment by maxiaolin0615** [comment]
Yes, anyone. Every button got the error I posted.

**Comment by MrHen** [comment]
I get the same problem. When I click on a button it generates this error: `TypeError: this.action is not a function`.


```
bower list
...
├─┬ textAngular#1.5.0
│ ├── angular#1.4.8 (1.5.1-build.4654+sha.f1aea54 available)
│ ├── font-awesome#4.5.0
│ └── rangy#1.3.0
```

**Comment by huynv86** [comment]
to fix this, you need add two css files:
	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,300">

**Comment by ospar0829** [comment]
I solve it, checking if textAngularSetup was loaded

**Comment by fresjitendra** [comment]
no it is not working @huynv86 i have also this problem toolbar buttons is not showing

**Comment by stevokk** [comment]
Hi @fresjitendra, your best chance of getting this resolved it to setup a plunkr demo showing your problems so people can help.

**Comment by segux** [comment]
I solved putting a conditionally if in Factory 'taToolExecuteAction'.


probably you have ng-repeat of all buttons, but not all buttons have actions, for example: 

this 2
![image](https://cloud.githubusercontent.com/assets/11930567/22825781/64d84386-ef8f-11e6-81ab-86fa87ecbae3.png)

in textAngular.umd.js:1520 before try cacth

**Comment by eug17** [comment]
solved adding inside try condition
` if (!this.action){
     return;
}`
