### ISSUE TITLE
mean.js project integration error 

### ISSUE THREAD

**Issue by skyees** [fraywing/textAngular#1196]
angular.js:4505 Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:
Error: [$injector:modulerr] Failed to instantiate module textAngular due to:
Error: [$injector:nomod] Module 'textAngular' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.11/$injector/nomod?p0=textAngular
    at http://localhost:3000/lib/angular/angular.js:68:12
    at http://localhost:3000/lib/angular/angular.js:2022:17
    at ensure (http://localhost:3000/lib/angular/angular.js:1946:38)
    at module (http://localhost:3000/lib/angular/angular.js:2020:14)
    at http://localhost:3000/lib/angular/angular.js:4482:22
    at forEach (http://localhost:3000/lib/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/lib/angular/angular.js:4466:5)
    at http://localhost:3000/lib/angular/angular.js:4483:40
    at forEach (http://localhost:3000/lib/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/lib/angular/angular.js:4466:5)
http://errors.angularjs.org/1.4.11/$injector/modulerr?p0=textAngular&p1=Err…s%20(http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangular%2Fangular.js%3A4466%3A5)
    at http://localhost:3000/lib/angular/angular.js:68:12
    at http://localhost:3000/lib/angular/angular.js:4505:15
    at forEach (http://localhost:3000/lib/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/lib/angular/angular.js:4466:5)
    at http://localhost:3000/lib/angular/angular.js:4483:40
    at forEach (http://localhost:3000/lib/angular/angular.js:341:20)
    at loadModules (http://localhost:3000/lib/angular/angular.js:4466:5)
    at createInjector (http://localhost:3000/lib/angular/angular.js:4391:11)
    at doBootstrap (http://localhost:3000/lib/angular/angular.js:1693:20)
    at Object.bootstrap (http://localhost:3000/lib/angular/angular.js:1714:12)
http://errors.angularjs.org/1.4.11/$injector/modulerr?p0=mean&p1=Error%3A%2…%20(http%3A%2F%2Flocalhost%3A3000%2Flib%2Fangular%2Fangular.js%3A1714%3A12)

**Comment by stevokk** [comment]
Without a reproducible case I don't think anybody will be willing to help on this, I suggest creating a plunkr as it seems more of an angular issue than textAngular itself.

**Comment by JoelParke** [comment]
I'm closing this as it has been a month and no plunkr or more info added.. Please reopen if still and issue.
