### ISSUE TITLE
Minified Version 1.5.1 Breaks Browserify

### ISSUE THREAD

**Issue by ccravens** [fraywing/textAngular#1219]
I use browserify to bundle my javascript dependencies.

When I attempt to bundle the 1.5.1minified version of textAngular, I get the following error:

```
Error: Parsing file C:\Users\user\project\bower_components\textAngular\dist\textAngular.min.js: Unexpected token (2:11834)
  at Deps.parseDeps (C:\Users\user\project\node_modules\browserify\node_modules\module-deps\index.js:437:28)
  at fromSource (C:\Users\user\project\node_modules\browserify\node_modules\module-deps\index.js:376:44)
  at C:\Users\user\project\node_modules\browserify\node_modules\module-deps\index.js:370:17
  at ConcatStream.<anonymous> (C:\Users\user\project\node_modules\browserify\node_modules\concat-stream\index.js:36:43)
  at emitNone (events.js:72:20)
  at ConcatStream.emit (events.js:166:7)
  at finishMaybe (C:\Users\user\project\node_modules\browserify\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:460:14)
  at endWritable (C:\Users\user\project\node_modules\browserify\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:469:3)
  at ConcatStream.Writable.end (C:\Users\user\project\node_modules\browserify\node_modules\concat-stream\node_modules\readable-stream\lib\_stream_writable.js:436:5)
  at DuplexWrapper.onend (C:\Users\user\project\node_modules\browserify\node_modules\duplexer2\node_modules\readable-stream\lib\_stream_readable.js:537:10)
  at DuplexWrapper.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at DuplexWrapper.emit (events.js:166:7)
  at C:\Users\user\project\node_modules\browserify\node_modules\duplexer2\node_modules\readable-stream\lib\_stream_readable.js:934:16
  at nextTickCallbackWith0Args (node.js:420:9)
  at process._tickCallback (node.js:349:13)
```

But when I include the regular version (not minified textAngular.js), it works! Anyone else getting this?

**Comment by frostme** [comment]
i can confirm this happens. Just got the same error

**Comment by pbassut** [comment]
That must have something to do with minifying(genius!). Maybe someone forgot to add a semi-colon or something of the like. Looks easy peasy.
