### ISSUE TITLE
unsafe.replace is not a function

### ISSUE THREAD

**Issue by tdespenza** [fraywing/textAngular#1335]
I'm using textAngular 1.5.10 and I'm getting this error below.
```
angular.js:13920 TypeError: unsafe.replace is not a function
    at taSanitize (http://localhost:9000/bower_components/textAngular/dist/textAngular.js:422:20)
    at Array._sanitize (http://localhost:9000/bower_components/textAngular/dist/textAngular.js:1840:37)
    at ngModelWatch (http://localhost:9000/bower_components/angular/angular.js:27810:36)
    at arguments.(anonymous function) (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1316:35)
    at Scope.$digest (http://localhost:9000/bower_components/angular/angular.js:17515:34)
    at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1364:23)
    at Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:17790:24)
    at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1427:22)
    at done (http://localhost:9000/bower_components/angular/angular.js:11831:47)
    at completeRequest (http://localhost:9000/bower_components/angular/angular.js:12033:7)
```
Do I need to add another dependency other than the required dependencies listed [here](https://github.com/fraywing/textAngular) for the bower install?

**Comment by JoelParke** [comment]
This is fixed with PR #1340.
