### ISSUE TITLE
Why ? The error is  Unknown provider: taRegisterToolProvider <- taRegisterTool

### ISSUE THREAD

**Issue by duoduodady** [fraywing/textAngular#1513]
Just as the follow,when I use the textAngular , it can't show on the html Page.
Then I open the console window, I find this error message.

Error: [$injector:unpr] Unknown provider: taRegisterToolProvider <- taRegisterTool
http://errors.angularjs.org/1.3.15/$injector/unpr?p0=taRegisterToolProvider%20%3C-%20taRegisterTool
    at http://localhost:400/config/app/js/base.js:9269:12
    at http://localhost:400/config/app/js/base.js:13221:19
    at Object.getService [as get] (http://localhost:400/config/app/js/base.js:13368:39)
    at http://localhost:400/config/app/js/base.js:13226:45
    at getService (http://localhost:400/config/app/js/base.js:13368:39)
    at Object.invoke (http://localhost:400/config/app/js/base.js:13400:13)
    at http://localhost:400/config/app/js/base.js:51025:26
    at Object.forEach (http://localhost:400/config/app/js/base.js:9529:20)
    at register (http://localhost:400/config/app/js/base.js:51024:15)
    at register (http://localhost:400/config/app/js/base.js:51004:11)

![image](https://cloud.githubusercontent.com/assets/13536089/25464429/e2591896-2b2e-11e7-8a10-76269db14752.png)

Now show my Codes

1  difined the module:

`     {
            name: 'textAngular', files: ['vendor/textAngular/dist/textAngular-rangy.min.js',
                                                        'vendor/textAngular/dist/textAngular-sanitize.js',
                                                       'vendor/textAngular/dist/textAngular.js',
                                                       'vendor/textAngular/dist/textAngularSetup.js',
                                                       'vendor/textAngular/dist/textAngular.css'], serie: true
        }

`
2 config the state 

 .state('app.AlphaRichTextAngular', {
            url: '/AlphaRichTextAngular',
            templateUrl: helper.basepath('richEditor2.html'),
            resolve: helper.resolveFor('textAngular')

        })

3  the html file:

<div ng-controller="AlphaStarTextditorController" class="panel panel-info">
    <div class="panel-heading" >test for the TextAngular</div>
    <div class="panel-body" id="commonGridContainerPanel">
        <h3>Editor</h3>
        <button ng-click="disabled = !disabled" unselectable>Disable text-angular Toggle</button>
        <div text-angular="text-angular" name="htmlcontent" ng-model="htmlcontent" ta-disabled='disabled'></div>
        <h3>Raw HTML in a text area</h3>
        <textarea ng-model="htmlcontent" style="width: 100%"></textarea>
        <h3>Bound with ng-bind-html</h3>
        <div ng-bind-html="htmlcontent"></div>
        <h3>Bound with ta-bind, our internal html-binding directive</h3>
        <div ta-bind="text" ng-model="htmlcontent" ta-readonly='disabled'></div>
        <button type="button" ng-click="htmlcontent = orightml">Reset</button>
        <p>Note: although we support classes and styles, angularjs' ng-bind-html directive will strip out all style attributes.</p>

        <h3>Option to masquerade as a fancy text-area - complete with form submission and optional ngModel</h3>
        <text-angular name="htmlcontent"><p>Any <b>HTML</b> we put in-between the text-angular tags gets automatically put into the editor if there <strong style="font-size: 12pt;"><u><em>is not</em></u></strong> a ngModel</p></text-angular>
    </div>
  
</div>

4  the controller:

App.controller('AlphaStarTextditorController', ['$scope', "$rootScope", function ($scope, $rootScope) {
    $scope.orightml = '<h2>Try me!</h2><p>textAngular is a super cool WYSIWYG Text Editor directive for AngularJS</p><p><b>Features:</b></p><ol><li>Automatic Seamless Two-Way-Binding</li><li>Super Easy <b>Theming</b> Options</li><li style="color: green;">Simple Editor Instance Creation</li><li>Safely Parses Html for Custom Toolbar Icons</li><li class="text-danger">Doesn&apos;t Use an iFrame</li><li>Works with Firefox, Chrome, and IE8+</li></ol><p><b>Code at GitHub:</b> <a href="https://github.com/fraywing/textAngular">Here</a> </p>';
    $scope.htmlcontent = $scope.orightml;
    $scope.disabled = false;
}]);

**Comment by duoduodady** [comment]
the html code:
`  <div text-angular="text-angular" name="htmlcontent" ng-model="htmlcontent" ></div>
`

**Comment by duoduodady** [comment]
The controller:

App.controller('AlphaStarTextditorController', ['$scope', "$rootScope", function ($scope, $rootScope) {
 $scope.htmlcontent = "hello textAngular!";
}]);

**Comment by stevenkissack** [comment]
@duoduodady This issue is really hard to read, in order to help make it clear for people can you tidy up your description and provide all code in a plunkr. Thanks
