### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by brandonros** [fraywing/textAngular#1553]
```
 TypeError: Cannot read property 'length' of undefined
      
      at ../../../../node_modules/textangular/dist/textAngular.umd.js:1146:22
      at ../../../../node_modules/textangular/dist/textAngular.umd.js:11:22
      at Object.<anonymous> (../../../../node_modules/textangular/dist/textAngular.umd.js:15:2)

```

I am trying to run unit tests that require() textAngular and I am getting this.

**Comment by brandonros** [comment]
The offending line of code is `if(_sheets[i].media.length === 0 || _sheets[i].media.mediaText.match(/(all|screen)/ig)){` and it happens when requiring textAngular for use with using jsDom/Jest.

Make it this: `if((_sheets[i].media || []).length === 0 || _sheets[i].media.mediaText.match(/(all|screen)/ig)){`

Doesn't seem to have any bad effect. Somebody should probably fix this?

**Comment by edm00se** [comment]
It's currently August of 2018, the last commit to the project looks to be from December of 2016. I think it's safe to say this isn't going to happen (here) anytime soon. I've run into the same thing and found that mocking the `styleSheets` property of `document` to an empty array seems to prevent the need to do much further. This is a bit heavy handed, but seems to do the trick.

In my `browser-mocks.js` file (which also mocks `localStorage`, with a couple other bits of miscellanea), I do the following:

```js
Object.defineProperty(document, 'styleSheets', {
  value: []
});
```

**Comment by ovanderzee** [comment]
When you decide to do the edit suggested by @brandonros, do not use the latest release. It has a breaking problem in the setup file. I used v1.5.12
