### ISSUE TITLE
Can't install via npm

### ISSUE THREAD

**Issue by kaelhem** [fraywing/textAngular#522]
Hi,

It seems that the installation via npm is broken.
Here's the stack trace:
```shell
 textangular@1.3.0-23 postinstall /.../node_modules/textangular
> node ./node_modules/bower/bin/bower install --allow-root

/
module.js:340
    throw err;
          ^
Error: Cannot find module '/.../node_modules/textangular/node_modules/bower/bin/bower'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! textangular@1.3.0-23 postinstall: `node ./node_modules/bower/bin/bower install --allow-root`
npm ERR! Exit status 8
```

**Comment by SimeonC** [comment]
Is this installing as `npm install textAngular` or the `npm install` for the dev environment?

**Comment by kaelhem** [comment]
This one is a "npm install textAngular". But both cases fail.

**Comment by SimeonC** [comment]
Ok thanks. I'll look into it.

**Comment by SimeonC** [comment]
Looks like my postinstall script is the culprit, patch coming out shortly.

**Comment by kaelhem** [comment]
It works ;) thanks!
