### ISSUE TITLE
Dependencies  issue in Text angular js

### ISSUE THREAD

**Issue by swangsuresh** [fraywing/textAngular#657]
am using angular js and angular -route .js above 1.3.x version but textangular lastest version show error:

Failed to instantiate module EDM due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.3.8-build.3697+sha.f297aa5/...)
    at Error (native)
    at http://localhost:8080/lottoadmin/resources/lib/angularjs/angular.min.js:6:439
    at http://localhost:8080/lottoadmin/resources/lib/angularjs/angular.min.js:36:98
    at s (http://localhost:8080/lottoadmin/resources/lib/angularjs/angular.min.js:7:322)
    at g (http://localhost:8080/lottoadmin/resources/lib/angularjs/angular.min.js:35:202)
    at http://localhost:8080/lottoadmin/resources/lib/angularjs/angular.min.js:35:371
    at s (http://localhost:8080/lottoadmin/resources/lib/angularjs/angular.min.js:7:322)
    at g (http://localhost:8080/lottoadmin/resources/lib/angularjs/angular.min.js:35:202)
    at Ob (http://localhost:8080/lottoadmin/resources/lib/angularjs/angular.min.js:38:435)
    at d (http://localhost:8080/lottoadmin/resources/lib/angularjs/angular.min.js:17:381
please fix it

**Comment by pbassut** [comment]
I'm using angular 1.3.15 and works just fine for me.

**Comment by swangsuresh** [comment]
Thanks Its working Fine Now
