### ISSUE TITLE
Rangy warning: Module SaveRestore: Marker element has been removed.

### ISSUE THREAD

**Issue by JoelParke** [fraywing/textAngular#733]
I am seeing this a lot recently:
rangy-core.js:129  Rangy warning: Module SaveRestore: Marker element has been removed. Cannot restore selection.

TO duplicate, simply create a text doc:

    <p>asdfasdf</p>
    <p>second</p>
    <p><span><br></span></p>

Then with the cursor at the end of the second, hit the indent button and you see:

    rangy-core.js:129  Rangy warning: Module SaveRestore: Marker element has been removed. Cannot restore selection.

Then hit the Decrease Indent button and you see:

    Error: Failed to execute 'insertBefore' on 'Node': Only one element on document allowed.
    at Error (native)
    at insertNodeAtPosition (http://parke.dynu.com:9000/bower_components/rangy/rangy-core.js:1025:19)
    at RangePrototype.util.extend.insertNode (http://parke.dynu.com:9000/bower_components/rangy/rangy-core.js:1512:41)
    at insertRangeBoundaryMarker (http://parke.dynu.com:9000/bower_components/rangy/rangy-selectionsaverestore.js:54:27)
    at saveRange (http://parke.dynu.com:9000/bower_components/rangy/rangy-selectionsaverestore.js:77:25)
    at saveRanges (http://parke.dynu.com:9000/bower_components/rangy/rangy-selectionsaverestore.js:144:33)
    at Object.saveSelection (http://parke.dynu.com:9000/bower_components/rangy/rangy-selectionsaverestore.js:172:30)
    at Scope.scope.startAction (http://parke.dynu.com:9000/bower_components/textAngular/dist/textAngular.js:2196:38)
    at Scope.executeAction (http://parke.dynu.com:9000/bower_components/textAngular/dist/textAngular.js:421:43)
    at $parseFunctionCall (http://parke.dynu.com:9000/bower_components/angular/angular.js:12404:18)(anonymous function) @ angular.js:11655(anonymous function) @ textAngular.js:427$parseFunctionCall @ angular.js:12404(anonymous function) @ hint.js:798Scope.$eval @ angular.js:14466Scope.$apply @ angular.js:14565scopePrototype.$apply @ hint.js:1478(anonymous function) @ hint.js:797jQuery.event.dispatch @ jquery.js:4435elemData.handle @ jquery.js:4121
 
I believe that there me some work going on to improve the Rangy restore selection when the html has changed.  Since I suspect this is at the heart of the issue... but I haven't had time to look yet.

**Comment by JoelParke** [comment]
I tried several smallish fixes for this, but it seems clear that something more substantial is needed.  The issue comes about when the cursor is not within an html element --in that case the html is clobbered and so rangy looses it's hidden marker.
