### ISSUE TITLE
TypeError a.indexof is not a function

### ISSUE THREAD

**Issue by dreadeddev** [fraywing/textAngular#755]
I am getting the above error message when using the textangular in an SPA model and loading 3 editors on different panels.

Hard to debug as it is not showing any of my code lines where the error is!

Thanks

Ian,

Full error below:

TypeError: a.indexOf is not a function
    at f (https://cdnjs.cloudflare.com/ajax/libs/textAngular/1.2.2/textAngular-sanitize.min.js:1:1035)
    at $get (https://cdnjs.cloudflare.com/ajax/libs/textAngular/1.2.2/textAngular-sanitize.min.js:1:142)
    at $get.getTrusted (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:133:118)
    at Object.$get.d.(anonymous function) [as getTrustedHtml] (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:134:326)
    at Object.fn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:214:395)
    at n.$get.n.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:123:356)
    at n.$get.n.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:126:293)
    at l (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:81:240)
    at M (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:85:342)
    at XMLHttpRequest.F.onload (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js:86:367)(anonymous function) @ angular.js:11655$get @ angular.js:8596$get.n.$digest @ angular.js:14326$get.n.$apply @ angular.js:14571l @ angular.js:9698M @ angular.js:9888F.onload @ angular.js:9829

**Comment by pbassut** [comment]
Could you set up a plunker with this so I can investigate further?

**Comment by pbassut** [comment]
I'm closing this issue since I got no response from the owner. I'll reopen if someone else have the same issue
